# Generated by Django 4.1.4 on 2023-07-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_delete_followerscount_profile_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followerscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
