# Generated by Django 4.1.4 on 2023-07-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_alter_post_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
